### ISSUE TITLE
get instance of ARCHETYPEID returns attributes and all operations as attributes

### ISSUE THREAD

**Issue by chevalleyc** [openEHR/archie#373]
F.e. calling a Archetyped::getArchetypeDetails() returns a structure containing:

```
archetypeId = {ArchetypeID@3036} "openEHR-EHR-OBSERVATION.body_temperature-zn.v1"
 namespace = null
 qualifiedRmEntity = "openEHR-EHR-OBSERVATION"
 domainConcept = "body_temperature-zn"
 rmOriginator = "openEHR"
 rmName = "EHR"
 rmEntity = "OBSERVATION"
 specialisation = null
 versionId = "1"
 value = "openEHR-EHR-OBSERVATION.body_temperature-zn.v1"
```
Where only value should be returned. This issue causes unproper object serialization on our side.

**Comment by pieterbos** [comment]
I assume you only mean the JSON, YAML and ODIN serialization of the archetype id, and not the java class that is returned? So, it should be:

```
"archetype_details":
   {
      "archetype_id": { "value": "openEHR-EHR-OBSERVATION.blood_pressure.v1"}, 
      "template_id": { "value": "..."},
      "rm_version": "1.1.0"
   }
```

the problem being that now some extra fields are added next to value? 

If so, those fields should not appear in the JSON if RMJacksonConfiguration.setAddExtraFieldsInArchetypeId is set to false, which is the default for the standards compliant output, which should solve your issue. Does it?

If you mean the java class: I think that how the java class implements those methods, by parsing once and caching them as it is now, or by parsing it every time a method is being called as you ask for, seems an implementation detail rather than a problem. Any reason why you consider this a problem?

**Comment by chevalleyc** [comment]
I think a java call in the form:

```
locatable.getArchetypeDetails().getArchetypeId()
```
should only return the attributes of the said object. In this scenario we get both attribute (`value`) and operations results. IMO this is not the expected behavior. WDYT?

**Comment by pieterbos** [comment]
I think it is in implementation detail. The current approach prevents parsing on every method call.

What is the problem you encounter with serialization?

**Comment by chevalleyc** [comment]
The issue is that with our DB encoding, we inherit from these non attributes and that causes discrepancies in our test suite (which was not observed before) as indicated above in this CR. We don't have this issue f.e. with DV_COUNT which support a number of operations (multiply, add etc.) that are not appearing when we perform the encoding. TBH I'm not keen to alter a working existing code.

**Comment by pieterbos** [comment]
DV_COUNT add and multiply operations have not yet been implemented in Archie, so there you will not see this problem indeed. 

They could perhaps be marked as transient, which the ArchieRMInfolookup could check on to check that it is a computed property rather than a full attribute.

Do you not have the same issue with the two attributes Pathable.parent and Pathable.parentAttributeName ? They also do not appear in the RM, but are essential for the Archie implementation.

**Comment by pieterbos** [comment]
Also without knowing more details about the problem you are having, it is very hard to me to understand the importance of this issue.

**Comment by chevalleyc** [comment]
Finally, I resolve to modify the encoding code, and used the parameter on RMJacksonConfiguration as you've indicated. Many thanks for your prompt response Pieter!
