### ISSUE TITLE
Differential form archetype has incorrect  "differential": false" set

### ISSUE THREAD

**Issue by MichielKlitsie** [openEHR/archie#41]
### Context
When trying to get the most basic building block of the archetypes (e.g. the differential-form) we noticed that the parameter `"differential": false,` was set in the response.body.

This should be `"differential": true`

### Solution
Set values to `true` in the following `exitArchetype` & `exitTemplate` codeblocks where `setDifferential` is used.

https://github.com/openEHR/archie/blob/75400f9df454bee5296a8e1c42237b71a10f5634/aom/src/main/java/com/nedap/archie/adlparser/treewalkers/ADLListener.java#L47-L62

**Comment by pieterbos** [comment]
Closing this issue since it has been solved as best as possible with the current OpenEHR specification, which has no way to mention that an archetype has been flattened in the ADL, except for with operational templates. Solution: parsed archetypes will always be marked differential, except for operational templates.
