### ISSUE TITLE
Serialisation of CBoolean with default value fails

### ISSUE THREAD

**Issue by VeraPrinsen** [openEHR/archie#447]
**Example:** 
CBoolean with a default value "true"

**After serialisation:** 
```
DV_BOOLEAN[id10] matches {
   value
}
```

We see that the serialisation of the default value is in the CComplexObjectSerializer, but the default value is however set in the CDefinedObject instead. We suspect that the serialisation of all CPrimitiveObjects could fail this way.

**Comment by pieterbos** [comment]
No default value is possible in the specification of ADL 2 on primitive values. Instead, you will have to add a default value for the nearest parent C_COMPLEX_OBJECT, in this case for the entire DV_CODED_TEXT. An assumed value is possible, but this is a different concept - it is the value that is assumed when it is not entered, rather than a to be prefilled default. See https://specifications.openehr.org/releases/AM/latest/ADL2.html#_default_values for examples.

So, I do not consider this is not a bug in Archie, other than that it does serialize an empty C_ATTRIBUTE perhaps.
