### ISSUE TITLE
grammar -> antlr-> revision history

### ISSUE THREAD

**Issue by pestiadam** [openEHR/archie#82]
Could you implementing revision_history section in the grammar?

**Comment by pieterbos** [comment]
It's easy to implement since it's generic ODIN -  So I could. I didn't know of anyone that used this specific feature. 

Do you have one or a few examples of an archetype that uses it, so I can check that I implement it correctly?

**Comment by pieterbos** [comment]
I discussed this with a few members of the specifications editorial committee, and they mentioned revision history is a candidate to be removed from the specification, because people generally use something like git to maintain different revisions of archetypes.

So could you explain why you need the revision_history support?

**Comment by pieterbos** [comment]
If you still want this, could you please respond to the earlier questions? Otherwise I will close this issue in a few days.

**Comment by pieterbos** [comment]
Closing this, see discussion above.
